name: Build Release

on:
   push:
      branches:
         - master
      tags:
         - "*"

jobs:
   build:
      runs-on: ubuntu-latest

      env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.OAUTH_TOKEN }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
         WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      steps:
         - uses: actions/checkout@v1
           with:
              fetch-depth: 150

         - name: Install and run Luacheck
           uses: nebularg/actions-luacheck@v1
           with:
              args: "--no-color -q"

         - name: Update CF Translations
           run: ./translations.sh

         - name: Generate Changelog
           run: ./generate_changelog.sh

         - name: Package And Release
           uses: BigWigsMods/packager@master
